### ISSUE TITLE
heap-buffer-overflow in cl_remap.c while changing 3D model in menu

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#1395]
```
==610343==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x936f438c at pc 0xf2c58c57 bp 0xffaa3998 sp 0xffaa3988
READ of size 4 at 0x936f438c thread T0
    #0 0xf2c58c56 in CL_CmpStudioTextures ../engine/client/cl_remap.c:55
    #1 0xf2c5c9b2 in CL_AllocRemapInfo ../engine/client/cl_remap.c:288
    #2 0xd8314f9c in R_StudioSetRemapColors ../ref/gl/gl_studio.c:2619
    #3 0xd8321fb9 in R_StudioDrawPlayer ../ref/gl/gl_studio.c:3401
    #4 0xd8324550 in R_StudioDrawModelInternal ../ref/gl/gl_studio.c:3532
    #5 0xd83248a5 in R_DrawStudioModel ../ref/gl/gl_studio.c:3558
    #6 0xd8266380 in R_DrawEntitiesOnList ../ref/gl/gl_rmain.c:834
    #7 0xd8267cad in R_RenderScene ../ref/gl/gl_rmain.c:978
    #8 0xd8269bda in R_RenderFrame ../ref/gl/gl_rmain.c:1115
    #9 0xf2d01410 in GL_RenderFrame ../engine/client/ref_common.c:59
    #10 0xf2bd7e0e in pfnRenderScene ../engine/client/cl_gameui.c:824
    #11 0xdf0a74a7 in EngFuncs::RenderScene(ref_viewpass_s const*) ../3rdparty/mainui/enginecallback_menu.h:274
    #12 0xdf0a6d08 in CMenuPlayerModelView::Draw() ../3rdparty/mainui/controls/PlayerModelView.cpp:204
    #13 0xdf08f38a in CMenuItemsHolder::Draw() ../3rdparty/mainui/controls/ItemsHolder.cpp:270
    #14 0xdf068503 in CMenuBaseWindow::Draw() ../3rdparty/mainui/controls/BaseWindow.cpp:127
    #15 0xdf083518 in CMenuFramework::Draw() ../3rdparty/mainui/controls/Framework.cpp:53
    #16 0xdf047713 in CWindowStack::Update() ../3rdparty/mainui/WindowSystem.cpp:169
    #17 0xdf01ca7e in UI_UpdateMenu(float) ../3rdparty/mainui/BaseMenu.cpp:687
    #18 0xf2bd2f53 in UI_UpdateMenu ../engine/client/cl_gameui.c:52
    #19 0xf2cafecd in V_PostRender ../engine/client/cl_view.c:539
    #20 0xf2c69553 in SCR_UpdateScreen ../engine/client/cl_scrn.c:547
    #21 0xf2bf079a in Host_ClientFrame ../engine/client/cl_main.c:3110
    #22 0xf27caed0 in Host_Frame ../engine/common/host.c:712
    #23 0xf27cdfef in Host_RunFrame ../engine/common/host_state.c:144
    #24 0xf27ce3e6 in COM_Frame ../engine/common/host_state.c:194
    #25 0xf27ccb55 in Host_Main ../engine/common/host.c:1268
    #26 0x5659370a in Sys_Start ../game_launch/game.cpp:179
    #27 0x56593746 in main ../game_launch/game.cpp:192
    #28 0xf6e2f518 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #29 0xf6e2f5f2 in __libc_start_main_impl ../csu/libc-start.c:392
    #30 0x565931ba in _start (/home/omarov/.xash/builtXash/xash3d+0x11ba)

0x936f438c is located 72 bytes to the right of 196-byte region [0x936f4280,0x936f4344)
allocated by thread T0 here:
    #0 0xf7992873 in __interceptor_malloc ../../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0xf29ec7fa in _Mem_Alloc ../engine/common/zone.c:110
    #2 0xf2c5cf33 in CL_AllocRemapInfo ../engine/client/cl_remap.c:294
    #3 0xd8314f9c in R_StudioSetRemapColors ../ref/gl/gl_studio.c:2619
    #4 0xd8321fb9 in R_StudioDrawPlayer ../ref/gl/gl_studio.c:3401
    #5 0xd8324550 in R_StudioDrawModelInternal ../ref/gl/gl_studio.c:3532
    #6 0xd83248a5 in R_DrawStudioModel ../ref/gl/gl_studio.c:3558
    #7 0xd826723d in R_DrawEntitiesOnList ../ref/gl/gl_rmain.c:904
    #8 0xd8267cad in R_RenderScene ../ref/gl/gl_rmain.c:978
    #9 0xd8269bda in R_RenderFrame ../ref/gl/gl_rmain.c:1115
    #10 0xf2d01410 in GL_RenderFrame ../engine/client/ref_common.c:59
    #11 0xf2bd7e0e in pfnRenderScene ../engine/client/cl_gameui.c:824
    #12 0xdf0a74a7 in EngFuncs::RenderScene(ref_viewpass_s const*) ../3rdparty/mainui/enginecallback_menu.h:274
    #13 0xdf0a6d08 in CMenuPlayerModelView::Draw() ../3rdparty/mainui/controls/PlayerModelView.cpp:204
    #14 0xdf08f38a in CMenuItemsHolder::Draw() ../3rdparty/mainui/controls/ItemsHolder.cpp:270
    #15 0xdf068503 in CMenuBaseWindow::Draw() ../3rdparty/mainui/controls/BaseWindow.cpp:127
    #16 0xdf083518 in CMenuFramework::Draw() ../3rdparty/mainui/controls/Framework.cpp:53
    #17 0xdf068aed in CMenuBaseWindow::DrawAnimation() ../3rdparty/mainui/controls/BaseWindow.cpp:149
    #18 0xdf086db7 in CMenuFramework::DrawAnimation() ../3rdparty/mainui/controls/Framework.cpp:188
    #19 0xdf0474b4 in CWindowStack::Update() ../3rdparty/mainui/WindowSystem.cpp:164
    #20 0xdf01ca7e in UI_UpdateMenu(float) ../3rdparty/mainui/BaseMenu.cpp:687
    #21 0xf2bd2f53 in UI_UpdateMenu ../engine/client/cl_gameui.c:52
    #22 0xf2cafecd in V_PostRender ../engine/client/cl_view.c:539
    #23 0xf2c69553 in SCR_UpdateScreen ../engine/client/cl_scrn.c:547
    #24 0xf2bf079a in Host_ClientFrame ../engine/client/cl_main.c:3110
    #25 0xf27caed0 in Host_Frame ../engine/common/host.c:712
    #26 0xf27cdfef in Host_RunFrame ../engine/common/host_state.c:144
    #27 0xf27ce3e6 in COM_Frame ../engine/common/host_state.c:194
    #28 0xf27ccb55 in Host_Main ../engine/common/host.c:1268
    #29 0x5659370a in Sys_Start ../game_launch/game.cpp:179

SUMMARY: AddressSanitizer: heap-buffer-overflow ../engine/client/cl_remap.c:55 in CL_CmpStudioTextures
Shadow bytes around the buggy address:
  0x326de820: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x326de830: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x326de840: fd fd fd fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x326de850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x326de860: 00 00 00 00 00 00 00 00 04 fa fa fa fa fa fa fa
=>0x326de870: fa[fa]fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x326de880: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x326de890: fd fd fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x326de8a0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x326de8b0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa fa
  0x326de8c0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==610343==ABORTING
```

**Comment by a1batross** [comment]
Fixed in 36ff819d
