### ISSUE TITLE
SDL2 Sanity fail (Xash3d)

### ISSUE THREAD

**Issue by ClutchRoadagain** [FWGS/xash3d-fwgs#1551]
I'm trying to set up Xash3d, I'm not used to sort of stuff and I've set the sdl in the same folder as my xash set-up, and things go as follows:

```
E:\projects\xash3d-fwgs-master>waf configure -T release --sdl2=e:\projects\xash3d-fwgs-master
Active code page: 65001
Using py
Setting top to                                          : E:\projects\xash3d-fwgs-master
Setting out to                                          : E:\projects\xash3d-fwgs-master\build
Build type                                              : humanrights
LTO build                                               : no
PolyOpt build                                           : no
Checking for 'msvc' (C compiler)                        : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x86\CL.exe
Target OS                                               : win32
Target CPU                                              : x86
Target binfmt                                           : pe
Checking for 'msvc' (C++ compiler)                      : C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x86\CL.exe
Target OS                                               : win32
Target CPU                                              : x86
Target binfmt                                           : pe
Checking for program 'cmake'                            : not found
Checking for program 'git'                              : C:\Program Files\Git\cmd\git.exe
Checking git hash                                       : no
Checking for program 'cmake'                            : not found
Checking if 'msvc' can target 32-bit                    : yes
Checking for required C flags                           : yes
Checking for required C++ flags                         : yes
Checking for header stdint.h                            : yes
Checking for header alloca.h                            : not found
Checking for header malloc.h                            : yes
Checking for MSVC library                               : user32
Checking for MSVC library                               : shell32
Checking for MSVC library                               : gdi32
Checking for MSVC library                               : advapi32
Checking for MSVC library                               : dbghelp
Checking for MSVC library                               : psapi
Checking for MSVC library                               : ws2_32
Checking for header tgmath.h                            : yes
Checking if tgmath.h is usable                          : yes
Checking for program 'pkg-config'                       : not found
--> public                                              : in progress
<-- public                                              : done
--> filesystem                                          : in progress
<-- filesystem                                          : done
--> engine                                              : in progress
Configuring SDL2 by provided path                       : yes: ['SDL2'], ['e:\\projects\\xash3d-fwgs-master\\lib\\x86'], ['e:\\projects\\xash3d-fwgs-master\\include', 'e:\\projects\\xash3d-fwgs-master\\include\\SDL2']
Checking for SDL2 sanity                                : no
SDL2 not available! If you want to build dedicated server, specify --dedicated
(complete log in E:\projects\xash3d-fwgs-master\build\config.log)
```
I checked the config.log & found this:
```
Checking for SDL2 sanity
==>

				#define SDL_MAIN_HANDLED
				#include <SDL.h>
				int main( void )
				{
					SDL_Init( SDL_INIT_EVERYTHING );
					return 0;
				}
<==
[1/2] Processing [32mbuild\conf_check_2cf3ea823e7ec3be6708c6d2bd15319d\test.c[0m

out: test.c

E:\projects\xash3d-fwgs-master\build\conf_check_2cf3ea823e7ec3be6708c6d2bd15319d\test.c(3): fatal error C1083: Cannot open include file: 'SDL.h': No such file or directory
from E:\projects\xash3d-fwgs-master\engine: Test does not build: Traceback (most recent call last):
  File "E:\projects\xash3d-fwgs-master\waf3-2.0.26-84a26fddc7f40e4e4f00569f36be455a\waflib\Configure.py", line 606, in run_build
    bld.compile()
  File "E:\projects\xash3d-fwgs-master\waf3-2.0.26-84a26fddc7f40e4e4f00569f36be455a\waflib\Build.py", line 359, in compile
    raise Errors.BuildError(self.producer.error)
waflib.Errors.BuildError: Build failed
 -> task in 'testprog' failed with exit status 2 (run with -v to display more information)

no
from E:\projects\xash3d-fwgs-master\engine: The configuration failed
from E:\projects\xash3d-fwgs-master\engine: SDL2 not available! If you want to build dedicated server, specify --dedicated
```
I feel in over my head, so any help would be appreciated!

**Comment by nekonomicon** [comment]
1. Did you clone repository via git or just download archive?
2. Are you sure you download development SDL2 package for Visual Studio?

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs#build-instructions

It literally says:

**NOTE: NEVER USE GitHub's ZIP ARCHIVES. GitHub doesn't include external dependencies we're using!**

**Download [SDL2](https://libsdl.org/download-2.0.php) development package for Visual Studio.**

**Configure build: waf configure -T release --sdl2=c:/path/to/SDL2**

I recommend you either reading the README.md, either using prebuilt versions, as in **most cases** you don't need to modify the engine.

**Comment by a1batross** [comment]
Closing due to no response.
