### ISSUE TITLE
Рандомное срабатывание assert failed на некоторых уровнях.

### ISSUE THREAD

**Issue by noname946** [FWGS/xash3d-fwgs#333]
Заметил, что на некоторых уровнях рандомно может сработать assert failed:
`Host_Error: assert failed at ../ref_soft/r_image.c:34`
Помимо этого, игра после этого вовсе вылетает, с руганью на GL_DeleteTexture.
К сожалению, но баг "плавающий" и точных последовательности действий для его вопроизведения я не могу пока найти, но было замечено, что наиболее часто это происходит на карте c1a0d после перехода из c1a0.
Backtrace:
```
Thread 1 "hl" received signal SIGSEGV, Segmentation fault.
GL_DeleteTexture (tex=0x807e9f60e220) at ../ref_soft/r_image.c:898
898             if( !tex->pixels[0]) return;
#0  GL_DeleteTexture (tex=0x807e9f60e220) at ../ref_soft/r_image.c:898
        prev = <optimized out>
        cur = <optimized out>
        i = <optimized out>
#1  0x00007ffff5531162 in GL_FreeTexture (texnum=<optimized out>) at ../ref_soft/r_image.c:1151
No locals.
#2  0x00007ffff55299ac in Mod_BrushUnloadTextures (mod=mod@entry=0x7ffff6faa3c0 <mod_known>) at ../ref_soft/r_context.c:273
        tx = 0x555557bc3a90
        i = 30
#3  0x00007ffff5529a0a in Mod_UnloadTextures (mod=mod@entry=0x7ffff6faa3c0 <mod_known>) at ../ref_soft/r_context.c:293
        i = <optimized out>
        j = <optimized out>
#4  0x00007ffff5529b0d in Mod_ProcessRenderData (mod=0x7ffff6faa3c0 <mod_known>, create=false, buf=0x0) at ../ref_soft/r_context.c:117
        loaded = true
#5  0x00007ffff6e9e18c in Mod_FreeUserData (mod=mod@entry=0x7ffff6faa3c0 <mod_known>) at ../engine/common/model.c:91
No locals.
#6  0x00007ffff6e9e283 in Mod_FreeModel (mod=mod@entry=0x7ffff6faa3c0 <mod_known>) at ../engine/common/model.c:109
No locals.
#7  0x00007ffff6e9e50f in Mod_FreeAll () at ../engine/common/model.c:161
        i = 0
#8  0x00007ffff6ed463b in SV_Shutdown (finalmsg=finalmsg@entry=0x7ffff6f3fb22 "Server was killed\n") at ../engine/server/sv_main.c:1074
No locals.
#9  0x00007ffff6e871be in Host_ShutdownServer () at ../engine/common/host.c:172
No locals.
#10 0x00007ffff6e87dc7 in Host_Error (error=0x7ffff5551075 "assert failed at %s:%i\n") at ../engine/common/host.c:714
        hosterror1 = "assert failed at ../ref_soft/r_image.c:34\n", '\000' <repeats 981 times>
        hosterror2 = "assert failed at ../ref_soft/r_image.c:34\n", '\000' <repeats 981 times>
        recursive = true
        argptr = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7ffffff78d20, reg_save_area = 0x7ffffff78c60}}
#11 0x00007ffff552fdb9 in R_GetTexture (texnum=1478311712) at ../ref_soft/r_image.c:34
No locals.
#12 0x00007ffff5548b9a in D_CacheSurface (surface=0x5555562017a0, miplevel=0) at ../ref_soft/r_surf.c:1307
        cache = <optimized out>
        maps = <optimized out>
#13 0x00007ffff552ce76 in D_SolidSurf (s=s@entry=0x7ffffff9c1c0) at ../ref_soft/r_edge.c:1203
No locals.
#14 0x00007ffff552d105 in D_DrawSurfaces () at ../ref_soft/r_edge.c:1291
        s = 0x7ffffff9c1c0
#15 0x00007ffff552d2a9 in R_ScanEdges () at ../ref_soft/r_edge.c:710
        iv = 425
        bottom = 767
        basespans = <error reading variable basespans (value requires 144032 bytes, which is more than max-value-size)>
        basespan_p = 0x7ffffff78da0
        s = <optimized out>
#16 0x00007ffff5533fd8 in R_EdgeDrawing () at ../ref_soft/r_main.c:1455
        ledges = <error reading variable ledges (value requires 224056 bytes, which is more than max-value-size)>
        lsurfs = <error reading variable lsurfs (value requires 176088 bytes, which is more than max-value-size)>
#17 0x00007ffff5535762 in R_RenderScene () at ../ref_soft/r_main.c:1621
No locals.
#18 0x00007ffff5535886 in R_RenderFrame (rvp=0x7fffffffdbc0) at ../ref_soft/r_main.c:1776
No locals.
#19 0x00007ffff6f2b6ea in GL_RenderFrame (rvp=rvp@entry=0x7fffffffdbc0) at ../engine/client/ref_common.c:60
No locals.
#20 0x00007ffff6f1bfdb in V_RenderView () at ../engine/client/cl_view.c:339
        rp = {vieworg = {-1563.16406, 311.984375, -199.251801}, viewangles = {12.7331543, 179.873657, 0}, forward = {-0.975404799, 0.00215081591, -0.22041066}, right = {0.00220504426, 0.999997556, -0}, up = {-0.220410123, 0.000486015255, 0.975407183}, 
          frametime = 0.0146175921, time = 1.38193047, intermission = 0, paused = 0, spectator = 0, onground = 1, waterlevel = 0, simvel = {-320, -1.625, 0}, simorg = {-1563.19531, 311.953125, -230.226562}, viewheight = {0, 0, 28}, idealpitch = 1.60000002, 
          cl_viewangles = {12.7331543, 179.873657, 0}, health = 100, crosshairangle = {0, 0, 0}, viewsize = 120, punchangle = {0, 0, 0}, maxclients = 1, viewentity = 1, playernum = 0, max_entities = 900, demoplayback = 0, hardware = 1, smoothing = 0, 
          cmd = 0x7ffff77f8bf4 <cl+1108884>, movevars = 0x7ffff76b9c10 <clgame+1296>, viewport = {0, 0, 1024, 768}, nextView = 0, onlyClientDraw = 0}
        rvp = {viewport = {0, 0, 1024, 768}, vieworigin = {-1563.16406, 311.984375, -199.251801}, viewangles = {12.7331543, 179.873657, 0}, viewentity = 1, fov_x = 90, fov_y = 73.7397919, flags = 1}
        viewnum = 0
#21 0x00007ffff6f135f5 in SCR_UpdateScreen () at ../engine/client/cl_scrn.c:520
No locals.
#22 0x00007ffff6f03421 in Host_ClientFrame () at ../engine/client/cl_main.c:3030
No locals.
#23 0x00007ffff6e87b6d in Host_Frame (time=time@entry=0.00105500105) at ../engine/common/host.c:642
No locals.
#24 0x00007ffff6e88c5d in Host_RunFrame (time=time@entry=0.00105500105) at ../engine/common/host_state.c:144
No locals.
#25 0x00007ffff6e88da5 in COM_Frame (time=0.00105500105) at ../engine/common/host_state.c:194
        oldState = 0
        loopCount = 0
#26 0x00007ffff6e88894 in Host_Main (argc=<optimized out>, argv=<optimized out>, progname=<optimized out>, bChangeGame=<optimized out>, func=<optimized out>) at ../engine/common/host.c:1107
        oldtime = 28.540650885000002
        newtime = 28.541705885999999
#27 0x0000555555555409 in Sys_Start () at ../game_launch/game.cpp:141
        ret = <optimized out>
        changeGame = <optimized out>
#28 main (argc=<optimized out>, argv=<optimized out>) at ../game_launch/game.cpp:153
No locals.
```

**Comment by lewa-j** [comment]
Забыл прикрепить полный лог.

**Comment by noname946** [comment]
@lewa-j 
[engine.txt](https://github.com/FWGS/xash3d-fwgs/files/6090643/engine.txt)

**Comment by a1batross** [comment]
У меня не происходит. 6_9

**Comment by mittorn** [comment]
Надо мне фиксы для asan залить будет

**Comment by noname946** [comment]
Баг более не проявляется, скорее всего исправили в коммите https://github.com/FWGS/xash3d-fwgs/commit/9313f7e80e0c33bc58298477d8e24b015502a295.
