### ISSUE TITLE
Краш при попытке запуска с параметром -nosound.

### ISSUE THREAD

**Issue by noname946** [FWGS/xash3d-fwgs#336]
При попытке запуска игры с параметром -nosound, происходит вылет.
Как я понял по backtrace и коду, краш происходит из-за того, что в engine/platform/sdl/events.c пытается идти проверка квара snd_mute_losefocus, но поскольку функция S_Init, где инициализируется этот квар завершает свою работу из-за -nosound до инициализации этого квара, то квар возвращает всегда NULL, от чего собственно и краш.

Backtrace:
```
Thread 1 "hl" received signal SIGSEGV, Segmentation fault.
0x00007ffff6ee4e07 in SDLash_ActiveEvent (gain=gain@entry=1) at ../engine/platform/sdl/events.c:344
344                     if( snd_mute_losefocus->value )
#0  0x00007ffff6ee4e07 in SDLash_ActiveEvent (gain=gain@entry=1) at ../engine/platform/sdl/events.c:344
No locals.
#1  0x00007ffff6ee5380 in SDLash_EventFilter (event=event@entry=0x7fffffffdd10) at ../engine/platform/sdl/events.c:620
No locals.
#2  0x00007ffff6ee53e4 in Platform_RunEvents () at ../engine/platform/sdl/events.c:658
        event = {type = 512, common = {type = 512, timestamp = 227}, display = {type = 512, timestamp = 227, display = 1, event = 12 '\f', padding1 = 127 '\177', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 0}, window = {type = 512, timestamp = 227, windowID = 1, 
            event = 12 '\f', padding1 = 127 '\177', padding2 = 0 '\000', padding3 = 0 '\000', data1 = 0, data2 = 0}, key = {type = 512, timestamp = 227, windowID = 1, state = 12 '\f', repeat = 127 '\177', padding2 = 0 '\000', padding3 = 0 '\000', keysym = {
              scancode = SDL_SCANCODE_UNKNOWN, sym = 0, mod = 15, unused = 0}}, edit = {type = 512, timestamp = 227, windowID = 1, text = "\f\177\000\000\000\000\000\000\000\000\000\000\017", '\000' <repeats 15 times>, "V\023×ö", start = 32767, length = 512}, text = {
            type = 512, timestamp = 227, windowID = 1, text = "\f\177\000\000\000\000\000\000\000\000\000\000\017", '\000' <repeats 15 times>, "V\023×ö"}, motion = {type = 512, timestamp = 227, windowID = 1, which = 32524, state = 0, x = 0, y = 15, xrel = 0, 
            yrel = 0}, button = {type = 512, timestamp = 227, windowID = 1, which = 32524, button = 0 '\000', state = 0 '\000', clicks = 0 '\000', padding1 = 0 '\000', x = 0, y = 15}, wheel = {type = 512, timestamp = 227, windowID = 1, which = 32524, x = 0, y = 0, 
            direction = 15}, jaxis = {type = 512, timestamp = 227, which = 1, axis = 12 '\f', padding1 = 127 '\177', padding2 = 0 '\000', padding3 = 0 '\000', value = 0, padding4 = 0}, jball = {type = 512, timestamp = 227, which = 1, ball = 12 '\f', 
            padding1 = 127 '\177', padding2 = 0 '\000', padding3 = 0 '\000', xrel = 0, yrel = 0}, jhat = {type = 512, timestamp = 227, which = 1, hat = 12 '\f', value = 127 '\177', padding1 = 0 '\000', padding2 = 0 '\000'}, jbutton = {type = 512, timestamp = 227, 
            which = 1, button = 12 '\f', state = 127 '\177', padding1 = 0 '\000', padding2 = 0 '\000'}, jdevice = {type = 512, timestamp = 227, which = 1}, caxis = {type = 512, timestamp = 227, which = 1, axis = 12 '\f', padding1 = 127 '\177', padding2 = 0 '\000', 
            padding3 = 0 '\000', value = 0, padding4 = 0}, cbutton = {type = 512, timestamp = 227, which = 1, button = 12 '\f', state = 127 '\177', padding1 = 0 '\000', padding2 = 0 '\000'}, cdevice = {type = 512, timestamp = 227, which = 1}, adevice = {type = 512, 
            timestamp = 227, which = 1, iscapture = 12 '\f', padding1 = 127 '\177', padding2 = 0 '\000', padding3 = 0 '\000'}, sensor = {type = 512, timestamp = 227, which = 1, data = {4.55758313e-41, 0, 0, 2.1019477e-44, 0, 0}}, quit = {type = 512, timestamp = 227}, 
          user = {type = 512, timestamp = 227, windowID = 1, code = 32524, data1 = 0x0, data2 = 0xf}, syswm = {type = 512, timestamp = 227, msg = 0x7f0c00000001}, tfinger = {type = 512, timestamp = 227, touchId = 139689516335105, fingerId = 0, x = 2.1019477e-44, 
            y = 0, dx = 0, dy = 0, pressure = -2.18112501e+33, windowID = 32767}, mgesture = {type = 512, timestamp = 227, touchId = 139689516335105, dTheta = 0, dDist = 0, x = 2.1019477e-44, y = 0, numFingers = 0, padding = 0}, dgesture = {type = 512, 
            timestamp = 227, touchId = 139689516335105, gestureId = 0, numFingers = 15, error = 0, x = 0, y = 0}, drop = {type = 512, timestamp = 227, file = 0x7f0c00000001 <error: Cannot access memory at address 0x7f0c00000001>, windowID = 0}, 
          padding = "\000\002\000\000ã\000\000\000\001\000\000\000\f\177\000\000\000\000\000\000\000\000\000\000\017", '\000' <repeats 15 times>, "V\023×öÿ\177\000\000\000\002\000\000â\000\000"}
#3  0x00007ffff6e87c52 in Host_RunFrame (time=time@entry=0.100000113) at ../engine/common/host_state.c:140
No locals.
#4  0x00007ffff6e87da5 in COM_Frame (time=0.100000113) at ../engine/common/host_state.c:194
        oldState = 0
        loopCount = 0
#5  0x00007ffff6e87894 in Host_Main (argc=<optimized out>, argv=<optimized out>, progname=<optimized out>, bChangeGame=<optimized out>, func=<optimized out>) at ../engine/common/host.c:1107
        oldtime = -0.042761716000000005
        newtime = 0.057238399000000002
#6  0x0000555555555409 in Sys_Start () at ../game_launch/game.cpp:141
        ret = <optimized out>
        changeGame = <optimized out>
#7  main (argc=<optimized out>, argv=<optimized out>) at ../game_launch/game.cpp:153
No locals.
```

**Comment by mittorn** [comment]
Вообще  nosound по идее неправильно реализован. Учитывается ли длина сентенсов если звук не инициализирован?

**Comment by noname946** [comment]
@mittorn Только что проверил, скрипты, которые используют сентенсы вроде-бы работают как положено, если по какой-то причине звук не инициализировался.

**Comment by a1batross** [comment]
Я вообще не уверен, зачем нужна эта опция.

Ну не проинициализируется аудио по причине отсутствия вообще звуковой подсистемы в ОС, от этого движок как раз не должен упасть.

Если необходимо заткнуть игру, достаточно выкрутить громкость в ноль.

**Comment by lewa-j** [comment]
@a1batross Похоже это наследие времён кваки, когда вычисление звука было тяжёлой задачей для некоторого железа.

**Comment by a1batross** [comment]
@lewa-j даже в таком случае нужно убедиться, что -nosound не просто отключает вывод звука на устройство, но отключает вообще всё, что связано со звуком.

Но даже так, мне кажется Half-Life без звука не имеет никакого смысла, так как текстовой подачи здесь нет.

**Comment by a1batross** [comment]
Fixed.
