### ISSUE TITLE
mod S.W.A.T not working

### ISSUE THREAD

**Issue by Skyrim-police** [FWGS/xash3d-fwgs#337]
mod crashing when i start new game
log: 
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/6097830/engine.log)
mod link: https://www.moddb.com/mods/swat2

**Comment by noname946** [comment]
Подтверждаю, краш действительно есть в случае этого мода.
Backtrace:
```
Thread 1 "hl" received signal SIGSEGV, Segmentation fault.
0x00007ffff6e70f0e in COM_ParseFile (data=0x55555615c6c0 'p' <repeats 200 times>..., token=0x7fffffffcbd0 'o' <repeats 12 times>, "pppppppppooooooooo", 'p' <repeats 12 times>, "oooooo", 'p' <repeats 15 times>, "ooo", 'p' <repeats 123 times>, 'o' <repeats 11 times>...)
    at ../engine/common/common.c:546
546                     token[len] = c;
#0  0x00007ffff6e70f0e in COM_ParseFile (data=0x55555615c6c0 'p' <repeats 200 times>..., 
    token=0x7fffffffcbd0 'o' <repeats 12 times>, "pppppppppooooooooo", 'p' <repeats 12 times>, "oooooo", 'p' <repeats 15 times>, "ooo", 'p' <repeats 123 times>, 'o' <repeats 11 times>...) at ../engine/common/common.c:546
        c = 112
        len = 9264
#1  0x00007ffff6ef3af6 in pfnParseFile (data=<optimized out>, token=<optimized out>) at ../engine/client/cl_game.c:3079
        out = <optimized out>
#2  0x00007ffff43a3fa9 in UTIL_FindEntityInMap (name=0x7ffff43b4f0e "trigger_camera", origin=0x7ffff43e35d4 <gHUD+5492>, angle=0x7ffff43e35e0 <gHUD+5504>) at ../cl_dll/hud_spectator.cpp:196
        n = <optimized out>
        found = 0
        keyname = '\000' <repeats 33 times>, "Îÿÿ\200\000\000\000\000Îÿÿÿ\177\000\000\000\000ÿÿÿ\177\000\000\000\000\000\000\000\000\000\000ÿÿÿÿÿÿÿÿpËÿÿÿ\177\000\000ÿÿÿÿÿÿÿÿ\000\000\000\000\000\000\000\000ÀËÿÿÿ\177\000\000ÀËÿÿÿ\177\000\000ÿÿÿÿ\000\000\000\000¸Ëÿÿÿ\177\000\000ÀËÿÿÿ\177\000\000\200ñÅ÷ÿ\177\000\000\000\000\000\000\000\000\000\000Ì\037èöÿ\177", '\000' <repeats 11 times>, "åxã#1>_ÀËÿÿÿ\177", '\000' <repeats 11 times>, "Îÿÿÿ\177\000\000"...
        token = 'o' <repeats 12 times>, "pppppppppooooooooo", 'p' <repeats 12 times>, "oooooo", 'p' <repeats 15 times>, "ooo", 'p' <repeats 123 times>, 'o' <repeats 270 times>...
        pEnt = <optimized out>
        data = 0x55555615a290 'o' <repeats 12 times>, "pppppppppooooooooo", 'p' <repeats 12 times>, "oooooo", 'p' <repeats 15 times>, "ooo", 'p' <repeats 123 times>, 'o' <repeats 11 times>...
#3  0x6f6f6f6f6f6f6f6f in ?? ()
No symbol table info available.
```

**Comment by lewa-j** [comment]
А теперь залей лог с нормальными переводами строк.

**Comment by Skyrim-police** [comment]
залил

**Comment by lewa-j** [comment]
Fixed by #469
