### ISSUE TITLE
Зависание нового сервера при заходе более чем одного игрока.

### ISSUE THREAD

**Issue by noname946** [FWGS/xash3d-fwgs#358]
Если на сервер пытается зайти больше чем одного игрока, то в некоторой долей вероятности может произойти зависание сервера.
Backtrace:
```
Thread 1 "xash" received signal SIGINT, Interrupt.
0x0000aaaaaab02f38 in Netchan_AddFragbufToTail (wait=0xaaaaab286240, buf=0xaaaabf27af50) at ../engine/common/net_chan.c:564
564                     while( p->next )
#0  0x0000aaaaaab02f38 in Netchan_AddFragbufToTail (wait=0xaaaaab286240, buf=0xaaaabf27af50) at ../engine/common/net_chan.c:564
        p = 0xaaaab8a49240
#1  0x0000aaaaaab03ac4 in Netchan_CreateFileFragmentsFromBuffer (chan=0xfffff6a45ab8, filename=0xaaaaab32ae20 "!MD5DCDFC2EE07B0901F2DA8524864BA1DCB", pbuf=0xaaaaab437d10 "LZSS8\024", size=1848) at ../engine/common/net_chan.c:924
        chunksize = -34
        send = -34
        pos = -171295
        remaining = 173143
        bufferid = 5038
        firstfragment = false
        wait = 0xaaaaab286240
        p = 0xaaaaab32ae24
        buf = 0xaaaabf27af50
#2  0x0000aaaaaab36094 in SV_DownloadFile_f (cl=0xfffff6a45888) at ../engine/server/sv_client.c:1992
        custResource = {szFileName = "logos/remapped.bmp", '\000' <repeats 45 times>, type = t_decal, nIndex = 0, nDownloadSize = 5176, ucFlags = 6 '\006', rgucMD5_hash = "\334\337\302\356\a\260\220\037-\250RHd\272", <incomplete sequence \313>, playernum = 0 '\000', 
          rguc_reserved = '\000' <repeats 31 times>, pNext = 0xfffff6a3fc40, pPrev = 0xfffff6a3fc40}
        md5 = "\334\337\302\356\a\260\220\037-\250RHd\272\035\313'c1\253\252\252\000\000\000\000\000\000\003dlf"
        pbuf = 0xaaaaab437d10 "LZSS8\024"
        size = 5176
        name = 0xaaaaab32ae20 "!MD5DCDFC2EE07B0901F2DA8524864BA1DCB"
#3  0x0000aaaaaab362fc in SV_ExecuteClientCommand (cl=0xfffff6a45888, s=0xaaaaaac6d480 <string> "dlfile !MD5DCDFC2EE07B0901F2DA8524864BA1DCB") at ../engine/server/sv_client.c:2100
        u = 0xaaaaaabb5a08 <ucmds+192>
#4  0x0000aaaaaab37c48 in SV_ExecuteClientMessage (cl=0xfffff6a45888, msg=0xaaaaaaeea8b0 <net_message>) at ../engine/server/sv_client.c:2562
        move_issued = false
        frame = 0xaaaaab5dd630
        c = 3
#5  0x0000aaaaaab509a0 in SV_ReadPackets () at ../engine/server/sv_main.c:434
        cl = 0xfffff6a45888
        i = 1
        qport = 48511
        curSize = 45
#6  0x0000aaaaaab51028 in Host_ServerFrame () at ../engine/server/sv_main.c:628
No locals.
#7  0x0000aaaaaaad73ec in Host_Frame (time=0.00106933701) at ../engine/common/host.c:641
No locals.
#8  0x0000aaaaaaad8988 in Host_RunFrame (time=0.00106933701) at ../engine/common/host_state.c:144
No locals.
#9  0x0000aaaaaaad8af8 in COM_Frame (time=0.00106933701) at ../engine/common/host_state.c:194
        oldState = 0
        loopCount = 0
#10 0x0000aaaaaaad8448 in Host_Main (argc=3, argv=0xfffffffff0f8, progname=0xaaaaaab7e128 "valve", bChangeGame=0, func=0xaaaaaaaef658 <Launcher_ChangeGame>) at ../engine/common/host.c:1107
        oldtime = 476986.06738079898
        newtime = 476986.06845013599
#11 0x0000aaaaaaaef784 in main (argc=3, argv=0xfffffffff0f8) at ../engine/common/launcher.c:113
        gamedir_buf = '\000' <repeats 31 times>
        gamedir = 0xaaaaaab7e128 "valve"
```

**Comment by mittorn** [comment]
Оба игрока одновременно загружают лого?

**Comment by noname946** [comment]
@mittorn Неа, висло, когда я был на сервере и пытался подключиться другой игрок, только заспавнился и всё, сервак встал.

**Comment by noname946** [comment]
Исправили в коммите https://github.com/FWGS/xash3d-fwgs/commit/f31e9ae19e0d9f3d8eccfb7735eaf44b54917fa7.
