### ISSUE TITLE
RADV crash in recent build with -rtx enabled

### ISSUE THREAD

**Issue by mittorn** [FWGS/xash3d-fwgs#690]
```
aco::(anonymous namespace)::get_sampler_desc (ctx=0xffff3b18, deref_instr=0xa083d90, desc_type=aco::(anonymous namespace)::ACO_DESC_SAMPLER, tex_instr=0xa083f00, write=false) at ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp:5867
5867    ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp: Нет такого файла или каталога.
(gdb) bt
#0  aco::(anonymous namespace)::get_sampler_desc (ctx=0xffff3b18, deref_instr=0xa083d90,
    desc_type=aco::(anonymous namespace)::ACO_DESC_SAMPLER, tex_instr=0xa083f00, write=false)
    at ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp:5867
#1  0xe0fcb0b8 in aco::(anonymous namespace)::tex_fetch_ptrs (stype=<synthetic pointer>, samp_ptr=<synthetic pointer>,
    res_ptr=<synthetic pointer>, instr=0xa083f00, ctx=0xffff3b18) at ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp:9119
#2  aco::(anonymous namespace)::visit_tex (ctx=ctx@entry=0xffff3b18, instr=instr@entry=0xa083f00)
    at ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp:9292
#3  0xe10272e9 in aco::(anonymous namespace)::visit_block (block=<optimized out>, ctx=<optimized out>)
    at ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp:10234
#4  aco::(anonymous namespace)::visit_cf_list (ctx=ctx@entry=0xffff3b18, list=<optimized out>, list=<optimized out>)
    at ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp:10699
#5  0xe10277da in aco::(anonymous namespace)::visit_if (if_stmt=0xa082b48, ctx=0xffff3b18)
    at ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp:10683
#6  aco::(anonymous namespace)::visit_cf_list (ctx=ctx@entry=0xffff3b18, list=<optimized out>, list=<optimized out>)
    at ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp:10701
#7  0xe10277da in aco::(anonymous namespace)::visit_if (if_stmt=0xa07c7a8, ctx=0xffff3b18)
    at ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp:10683
#8  aco::(anonymous namespace)::visit_cf_list (ctx=ctx@entry=0xffff3b18, list=<optimized out>, list=<optimized out>)
    at ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp:10701
#9  0xe102c82b in aco::(anonymous namespace)::visit_loop (ctx=ctx@entry=0xffff3b18, loop=loop@entry=0x9e5f048)
    at ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp:10316
#10 0xe1027789 in aco::(anonymous namespace)::visit_cf_list (ctx=ctx@entry=0xffff3b18, list=<optimized out>, list=<optimized out>)
    at ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp:10704
#11 0xe1028485 in aco::select_program (program=0x85986b0, shader_count=1, shaders=0xffff66a4, config=0xffff4bec, options=0xffff4da0,
    info=0xffff84c0, args=0xffff50c0) at ../mesa-9999/src/amd/compiler/aco_instruction_selection.cpp:11675
#12 0xe0ed3c9c in aco_compile_shader (options=<optimized out>, info=<optimized out>, shader_count=<optimized out>,
    shaders=<optimized out>, args=<optimized out>, binary=<optimized out>) at ../mesa-9999/src/amd/compiler/aco_interface.cpp:101
#13 0xe0b7f83f in shader_compile (gs_copy_shader=false, trap_handler_shader=false, stage=<optimized out>, binary_out=0xffff6720,
    keep_statistic_info=false, keep_shader_info=false, options=0xffff4da0, info=0xffff84c0, shader_count=1, shaders=0xffff66a4,
    module=0xffffb844, device=0x83c02a0) at ../mesa-9999/src/amd/vulkan/radv_shader.c:1812
#14 radv_shader_compile (device=0x83c02a0, module=0xffffb844, shaders=0xffff66a4, shader_count=1, layout=0x8647d70, key=0xffffb198,
    info=0xffff84c0, keep_shader_info=false, keep_statistic_info=false, binary_out=0xffff6720)
    at ../mesa-9999/src/amd/vulkan/radv_shader.c:1878
#15 0xe0b609d4 in radv_create_shaders (pipeline=0x9c75c60, pipeline_layout=0x8647d70, device=0x83c02a0, cache=0x85d2170,
    pipeline_key=0xffffb198, pStages=0xffffb128, flags=0, custom_hash=0xffffb830 "9\325WC\310\372\365\234\026O,|\026\"/i\024\202%\277",
    pipeline_feedback=0x0, stage_feedbacks=0xffffb160) at ../mesa-9999/src/amd/vulkan/radv_pipeline.c:3686
#16 0xe0b671d3 in radv_compute_pipeline_create (_device=0x83c02a0, _cache=140321136, pCreateInfo=0xffffb8c0, pAllocator=0x0,
    custom_hash=0xffffb830 "9\325WC\310\372\365\234\026O,|\026\"/i\024\202%\277", rt_stack_sizes=0x8646f50, rt_group_count=5,
    pPipeline=0xe2ed8b3c <g_rtx+508>) at ../mesa-9999/src/amd/vulkan/radv_pipeline.c:5820
#17 0xe0b7977c in radv_rt_pipeline_create (pPipeline=0xe2ed8b3c <g_rtx+508>, pAllocator=0x0, pCreateInfo=0xffffbcc0, _cache=140321136,
    _device=0x83c02a0) at ../mesa-9999/src/amd/vulkan/radv_pipeline_rt.c:2243
#18 radv_CreateRayTracingPipelinesKHR (_device=0x83c02a0, deferredOperation=0, pipelineCache=140321136, count=1,
    pCreateInfos=0xffffbcc0, pAllocator=0x0, pPipelines=0xe2ed8b3c <g_rtx+508>) at ../mesa-9999/src/amd/vulkan/radv_pipeline_rt.c:2305
#19 0xe14b3849 in createPipeline () at ../ref_vk/vk_rtx.c:447
#20 0xe14b56f7 in VK_RayInit () at ../ref_vk/vk_rtx.c:1022
#21 0xe14a64a8 in R_VkInit () at ../ref_vk/vk_core.c:713
#22 0xf6e24d0d in R_LoadProgs (name=0xffffc450 "libref_vk.so") at ../engine/client/ref_common.c:478
#23 R_LoadRenderer (refopt=refopt@entry=0xffffc590 "vk") at ../engine/client/ref_common.c:550
#24 0xf6e25467 in R_Init () at ../engine/client/ref_common.c:683
#25 0xf6e347ed in VID_Init () at ../engine/client/vid_common.c:195
#26 0xf6df3b40 in CL_Init () at ../engine/client/cl_main.c:3072
#27 0xf6d4b631 in Host_Main (argc=10, argv=0xffffc904, progname=0x804a058 "valve", bChangeGame=0,
    func=0x8049370 <Sys_ChangeGame(char const*)>) at ../engine/common/host.c:1083
#28 0x0804917e in Sys_Start () at ../game_launch/game.cpp:146
#29 main (argc=10, argv=0xffffc904) at ../game_launch/game.cpp:159
```

**Comment by zgdump** [comment]
Мне думается, такие issue нужно кидать в форк vk+rtx

**Comment by mittorn** [comment]
Ну да, я вкладку перепутал, теперь фз как переместить

**Comment by zgdump** [comment]
> Ну да, я вкладку перепутал, теперь фз как переместить

А мы вчера гадали, почему это тут.... Закрой issue тут, открой issue там
