### ISSUE TITLE
Не работает сборка

### ISSUE THREAD

**Issue by AruMoon** [FWGS/xash3d-fwgs#691]
```
Build commands will be stored in build/compile_commands.json
Waf: Entering directory `/home/arumoon/Документы/xash3d-fwgs/build'
[356/356] Linking build/engine/libxash.so
/usr/bin/ld: пропускается несовместимый /usr/lib/libm.so при поиске -lm
/usr/bin/ld: пропускается несовместимый /usr/lib/libm.a при поиске -lm
/usr/bin/ld: пропускается несовместимый /usr/lib/libdl.so при поиске -ldl
/usr/bin/ld: пропускается несовместимый /usr/lib/libdl.a при поиске -ldl
/usr/bin/ld: пропускается несовместимый /usr/lib/libSDL2.so при поиске -lSDL2
/usr/bin/ld: пропускается несовместимый /usr/lib/libgcc_s.so.1 при поиске libgcc_s.so.1
/usr/bin/ld: пропускается несовместимый /usr/lib/libgcc_s.so.1 при поиске libgcc_s.so.1
/usr/bin/ld: пропускается несовместимый /usr/lib/libpthread.so при поиске -lpthread
/usr/bin/ld: пропускается несовместимый /usr/lib/libpthread.a при поиске -lpthread
/usr/bin/ld: пропускается несовместимый /usr/lib/libc.so при поиске -lc
/usr/bin/ld: пропускается несовместимый /usr/lib/libc.a при поиске -lc
/usr/bin/ld: пропускается несовместимый /usr/lib/libgcc_s.so.1 при поиске libgcc_s.so.1
/usr/bin/ld: пропускается несовместимый /usr/lib/libgcc_s.so.1 при поиске libgcc_s.so.1
```

**Comment by a1batross** [comment]
Not a bug. Build 64 bit version.

**Comment by mittorn** [comment]
Что не работает то? Тут нет ошибок

**Comment by AruMoon** [comment]
Раньше собирало 32 бит

**Comment by AruMoon** [comment]
Проблема другая, лог выше это уже при второй попытке продолжить сборку
Вот то что выводит в первый раз, оно пытается установить xash3d в `/xash3d`
```
[355/363] Compiling engine/common/model.c
01:53:47 runner ['/usr/bin/gcc', '-m32', '-g', '-fvisibility=hidden', '-O3', '-fdiagnostics-color=always', '-Werror=return-type', '-Werror=parentheses', '-Werror=vla', '-Werror=tautological-compare', '-Werror=duplicated-cond', '-Werror=duplicated-branches', '-Werror=bool-compare', '-Werror=bool-operation', '-Wcast-align', '-Werror=cast-align=strict', '-Werror=packed', '-Werror=packed-not-aligned', '-Wuninitialized', '-Winit-self', '-Werror=implicit-fallthrough=2', '-Werror=logical-op', '-Werror=write-strings', '-Wstrict-aliasing', '-Werror=incompatible-pointer-types', '-Werror=implicit-function-declaration', '-Werror=int-conversion', '-Werror=implicit-int', '-Werror=strict-prototypes', '-Werror=old-style-declaration', '-Werror=old-style-definition', '-Werror=declaration-after-statement', '-Werror=enum-conversion', '-Werror=jump-misses-init', '-fPIC', '-pthread', '-Iengine/common', '-I../engine/common', '-Iengine/server', '-I../engine/server', '-Iengine/client', '-I../engine/client', '-Iengine/client/vgui', '-I../engine/client/vgui', '-Iengine/tests', '-I../engine/tests', '-Iengine', '-I../engine', '-Ipublic', '-I../public', '-Icommon', '-I../common', '-Ipm_shared', '-I../pm_shared', '-I/usr/include/SDL2', '-DHAVE_STDINT_H=1', '-DSTDINT_H="stdint.h"', '-DHAVE_TGMATH_H=1', '-DHAVE_ALLOCA_H=1', '-DALLOCA_H="alloca.h"', '-DXASH_BUILD_COMMIT="f601127-dirty"', '-DXASH_LOW_MEMORY=0', '-DHAVE_SDL2=1', '-DXASH_SDL=2', '-D_REENTRANT', '../engine/common/model.c', '-c', '-o/home/arumoon/Документы/xash3d-fwgs/build/engine/common/model.c.1.o']
+ install /xash3d (from build/game_launch/xash3d)
Waf: Leaving directory `/home/arumoon/Документы/xash3d-fwgs/build'
Build failed
Traceback (most recent call last):
  File "/home/arumoon/Документы/xash3d-fwgs/.waf3-2.0.22-c7da3f216d29d06f37ce7acc9d571eeb/waflib/Build.py", line 1197, in do_install
    self.copy_fun(src, tgt)
  File "/home/arumoon/Документы/xash3d-fwgs/.waf3-2.0.22-c7da3f216d29d06f37ce7acc9d571eeb/waflib/extras/strip_on_install.py", line 44, in copy_fun
    inst_copy_fun(self, src, tgt)
  File "/home/arumoon/Документы/xash3d-fwgs/.waf3-2.0.22-c7da3f216d29d06f37ce7acc9d571eeb/waflib/Build.py", line 1093, in copy_fun
    shutil.copy2(src, tgt)
  File "/usr/lib/python3.9/shutil.py", line 443, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/xash3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arumoon/Документы/xash3d-fwgs/.waf3-2.0.22-c7da3f216d29d06f37ce7acc9d571eeb/waflib/Task.py", line 354, in process
    ret = self.run()
  File "/home/arumoon/Документы/xash3d-fwgs/.waf3-2.0.22-c7da3f216d29d06f37ce7acc9d571eeb/waflib/Build.py", line 1128, in run
    fun(x.abspath(), y.abspath(), x.path_from(launch_node))
  File "/home/arumoon/Документы/xash3d-fwgs/.waf3-2.0.22-c7da3f216d29d06f37ce7acc9d571eeb/waflib/Build.py", line 1203, in do_install
    raise Errors.WafError('Could not install the file %r' % tgt, e)
waflib.Errors.WafError: Could not install the file '/xash3d'
```

**Comment by AruMoon** [comment]
Проблему уже решил, не заметил что теперь надо destdir писать вместо prefix

**Comment by AruMoon** [comment]
А нет
