### ISSUE TITLE
Issue when compiling from source on Linux: ModuleNotFoundError: No module named 'compiler_optimizations'

### ISSUE THREAD

**Issue by z4ppatron** [FWGS/xash3d-fwgs#863]
I am on Manjaro Linux with an Intel processor. 

I have so far followed the tutorial for compiling under linux, and as soon as i write `waf configure -T release` under the xash3d-fwgs folder, i get the error `ModuleNotFoundError: No module named 'compiler_optimizations'`. The module does exist under scripts/waifulib, so i haven't changed any code or moved anything around.

Any ideas?

**Comment by a1batross** [comment]
Can you post full log?

чт, 2 июн. 2022 г., 16:21 z4ppatron ***@***.***>:

**Comment by z4ppatron** [comment]
Here it is:
```
$ waf configure -T -8 release
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/waf/waflib/Scripting.py", line 159, in waf_entry_point
    run_commands()
  File "/lib/python3.10/site-packages/waf/waflib/Scripting.py", line 251, in run_commands
    parse_options()
  File "/lib/python3.10/site-packages/waf/waflib/Scripting.py", line 217, in parse_options
    ctx.execute()
  File "/lib/python3.10/site-packages/waf/waflib/Options.py", line 356, in execute
    super(OptionsContext, self).execute()
  File "/lib/python3.10/site-packages/waf/waflib/Context.py", line 214, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/lib/python3.10/site-packages/waf/waflib/Context.py", line 296, in recurse
    user_function(self)
  File "/home/agd/.xash3d/xash3d-fwgs/wscript", line 109, in options
    opt.load('compiler_optimizations subproject')
  File "/lib/python3.10/site-packages/waf/waflib/Context.py", line 204, in load
    module = load_tool(t, path, with_sys_path=with_sys_path)
  File "/lib/python3.10/site-packages/waf/waflib/Context.py", line 734, in load_tool
    __import__(tool)
ModuleNotFoundError: No module named 'compiler_optimizations'

```

**Comment by a1batross** [comment]
How did you get waf installed into site-packages? Don't do that, use one that's included with the source.

**Comment by z4ppatron** [comment]
Oops, right, didn't see the `./`. It seems to work now, thanks!
