### ISSUE TITLE
Xash3D crashes when launching game

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#94]
Xash3D crashes when launching game on Android
Crash log:
===============================
time: 1575368028463
msg: java.lang.SecurityException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:5948)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1259)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:914)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:13969)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2806)

stacktrace: java.lang.RuntimeException: Unable to start service su.xash.engine.XashService@42b5801 with Intent { cmp=su.xash.engine/.XashService }: java.lang.SecurityException: Permission Denial: startForeground from pid=27203, uid=10144 requires android.permission.FOREGROUND_SERVICE
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
	at android.app.ActivityThread.access$1800(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=27203, uid=10144 requires android.permission.FOREGROUND_SERVICE
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6176)
	at android.app.Service.startForeground(Service.java:707)
	at su.xash.engine.XashService.onStartCommand(XashService.java:93)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:5948)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1259)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:914)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:13969)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2806)

**Comment by mittorn** [comment]
https://github.com/FWGS/xash3d-android-project/pull/195
